# Generated by Django 2.0 on 2018-01-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('sq_meters', models.PositiveIntegerField(verbose_name='大小/平方米')),
                ('nr_floors', models.PositiveSmallIntegerField(default=1, verbose_name='层高')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='修建年代')),
                ('house_color_outside', models.CharField(max_length=20, verbose_name='屋体颜色')),
                ('distance_to_nearest_kindergarten', models.PositiveIntegerField(blank=True, null=True, verbose_name='最近幼儿园距离')),
                ('distance_to_nearest_school', models.PositiveIntegerField(blank=True, null=True, verbose_name='最近学校距离')),
                ('distance_to_nearest_hospital', models.PositiveIntegerField(blank=True, null=True, verbose_name='最近医院距离')),
                ('has_cellar', models.BooleanField(default=False, verbose_name='地下室')),
                ('has_pool', models.BooleanField(default=False, verbose_name='停车场')),
                ('has_garage', models.BooleanField(default=False, verbose_name='车库')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='house_price.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
